In [1]:
from e3nn import o3

In [7]:
irrep = o3.Irreps('4x0e + 4x1o + 4x2e')

irrep

irrep.slices()

[slice(0, 4, None), slice(4, 16, None), slice(16, 36, None)]

In [8]:
from allegro.nn._strided._layout import StridedLayout

In [10]:
strided_irrep = StridedLayout(irrep, pad_to_multiple= 1)

In [14]:
# Seems like a major format. You can represent inexed in the form n m l
strided_irrep.indexes_to_strided.reshape((4, 9))

tensor([[ 0,  4,  5,  6, 16, 17, 18, 19, 20],
        [ 1,  7,  8,  9, 21, 22, 23, 24, 25],
        [ 2, 10, 11, 12, 26, 27, 28, 29, 30],
        [ 3, 13, 14, 15, 31, 32, 33, 34, 35]])

In [19]:
# transform back
strided_irrep.indexes_to_catted

tensor([ 0,  9, 18, 27,  1,  2,  3, 10, 11, 12, 19, 20, 21, 28, 29, 30,  4,  5,
         6,  7,  8, 13, 14, 15, 16, 17, 22, 23, 24, 25, 26, 31, 32, 33, 34, 35])

In [29]:
# this one is fine but do not set high spherical harmonics in right order
import numpy as np
np.array(range(36)).reshape((9, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [1]:
instr = []
# Instructions
irreps_in = o3.Irreps('4x0e + 4x1o + 4x2e')
irreps_mid = o3.Irreps('4x0e + 4x1o + 4x2e')
irreps_out = o3.Irreps('4x0e + 4x1o + 4x2e')

for (_, ir_in) in irreps_in:
    for (_, ir_in) in irreps_in:
        for (_, ir_in) in irreps_in: